name: Deploy package on tag released

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy-on-tag:
    uses: ./.github/workflows/deploy.yaml
    with:
      version: ${{ github.ref_name }}
    secrets: inherit

  trigger-vllm-rbln-pkg-update:
    name: trigger vllm-rbln pkg update PR
    needs: [deploy-on-tag]
    runs-on: rbln-sw-k8s-4c-32gb
    container:
      image: ${{ vars.DEV_CONTAINER_IMAGE }}
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: 'rbln-sw',
              repo: 'vllm-rbln',
              workflow_id: 'dispatch_pkg_update.yaml',
              ref: 'dev',
              inputs: {
                'python-version': '3.12',
                'optimum-version': '${{ github.ref_name }}',
              }
            })
            console.log(result)

